# Generated by Django 3.2.4 on 2022-03-03 19:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220228_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 19, 51, 50, 230568, tzinfo=utc)),
        ),
    ]
